/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CropsRouteImport } from './routes/crops'
import { Route as CropsSlugRouteImport } from './routes/crops.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsRoute = CropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsSlugRoute = CropsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CropsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crops': typeof CropsRouteWithChildren
  '/crops/$slug': typeof CropsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crops': typeof CropsRouteWithChildren
  '/crops/$slug': typeof CropsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crops': typeof CropsRouteWithChildren
  '/crops/$slug': typeof CropsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crops' | '/crops/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crops' | '/crops/$slug'
  id: '__root__' | '/' | '/crops' | '/crops/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CropsRoute: typeof CropsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops': {
      id: '/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof CropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops/$slug': {
      id: '/crops/$slug'
      path: '/$slug'
      fullPath: '/crops/$slug'
      preLoaderRoute: typeof CropsSlugRouteImport
      parentRoute: typeof CropsRoute
    }
  }
}

interface CropsRouteChildren {
  CropsSlugRoute: typeof CropsSlugRoute
}

const CropsRouteChildren: CropsRouteChildren = {
  CropsSlugRoute: CropsSlugRoute,
}

const CropsRouteWithChildren = CropsRoute._addFileChildren(CropsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CropsRoute: CropsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
